version: '3.7'
services:
  nginx:
    build:
      context: ./nginx
      args:
        html_dir: ${HTML_DIR}
    ports:
      - "8080:80"
    volumes: 
      - html_data:${HTML_DIR}
    depends_on:
      - php7_inst1
      - php7_inst2
    networks:
      - my_web

  php7_inst1:
    build:
      context: ./php7
      args:
        html_dir: ${HTML_DIR}
    ports:
      - "9001:9000"
    volumes:
      - html_data:${html_dir}
    networks:
      - my_web

  php7_inst2:
    build:
      context: ./php7
      args:
        html_dir: ${HTML_DIR}
    ports:
      - "9000:9000"
    volumes:
      - html_data:${HTML_DIR}
    networks:
      - my_web

  lb:
    build:
      context: ./haproxy
    ports:
      - "80:80"
    depends_on:
      - nginx
      - php7_inst1
      - php7_inst2
    networks:
      - my_web
    # volumes:
    #   - 

volumes:
  html_data:

networks:
  my_web:
    driver: bridge